### ISSUE TITLE
status 별 우선순위 조정

### ISSUE THREAD

**Issue by shlee322** [shlee322/delivery-tracker#104]
시간 순 데이터가 아니라 delivered 상태를 최우선으로 조정하는 옵션 제공

**Comment by nain311** [comment]
바쁘신데 정말 죄송한데..
반품할때 해당 운송장을 그대로 사용하는 경우가 있습니다.
- 수거
- 배송중
- 배달
- 완료
- 수거
- 배송중
- 배달
- 완료
이런식으로 순서로 이루어 질때가 있는데.. Delivered이후 Pick_up이 다시 있을경우 다시 마지막 상태로 볼 수 있도록 해주실 수 있을까요?

**Comment by shlee322** [comment]
@nain311 오호 그런 경우가 있군요. 감사합니다. 고려하도록 하겠습니다.

**Comment by shlee322** [comment]
v2023에서 lastEvent 제공에 따라 close 합니다.
