### ISSUE TITLE
한진택배가 이상하게 안되는 것 같습니다~

### ISSUE THREAD

**Issue by ryol84** [shlee322/delivery-tracker#107]
https://www.hanjin.co.kr/kor/CMS/DeliveryMgr/WaybillResult.do?mCode=MN038&wblnum=510683980391&schLang=KR&wblnumText=

다음과 같이 배송완료 되었는데~

언젠가부터 

connect ECONNREFUSED 211.210.94.28:443

라고 나오면서 한진이 트랙킹이 안되는 것 같습니다 ^^ 

롯데는 또 잘되더라구요~

**Comment by shlee322** [comment]
확인해보도록 하겠습니다. 감사합니다. #103

**Comment by shlee322** [comment]
기존 한진택배 사이트가 변경되어 재개발이 필요한 상황으로 판단됩니다.
추가하여 PR 올려주시거나 다음 버전 배포시까지 기다려주시면 감사하겠습니다.

**Comment by ryol84** [comment]
> 기존 한진택배 사이트가 변경되어 재개발이 필요한 상황으로 판단됩니다.
> 추가하여 PR 올려주시거나 다음 버전 배포시까지 기다려주시면 감사하겠습니다.

다음버전까지 기다리겠습니다~~ 감사합니다~

**Comment by shlee322** [comment]
#121 에서 처리 예정입니다.

**Comment by shlee322** [comment]
처리 완료되었습니다.
