### ISSUE TITLE
우체국 택배 조회 안됨

### ISSUE THREAD

**Issue by navergirugi** [shlee322/delivery-tracker#108]
어제부터 우체국 택배가 안되는거 같습니다. 6월8일

**Comment by shlee322** [comment]
확인해보도록 하겠습니다. 감사합니다.

**Comment by ejoonie** [comment]
const $informationTable = $('.table_col:nth-child(2)'); ==> const $informationTable = $('.table_col:nth-child(3)'); 으로 바뀐듯 합니다.

**Comment by ejoonie** [comment]
```
        const $informationTable = $("#print").find('table');
        const $progressTable = $('#processTable');
```
이렇게 하면 어떨까요?
