### ISSUE TITLE
npm으로 설치시 에러가 나는데  ㅠㅠ

### ISSUE THREAD

**Issue by joongkeun** [shlee322/delivery-tracker#12]
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v10.15.0/lib/node_modules/delivery-tracker-apiserver/node_modules/iconv/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v10.15.0/lib/node_modules/delivery-tracker-apiserver/node_modules/iconv/.node-gyp'
gyp ERR! System Linux 2.6.32-642.13.1.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v10.15.0/bin/node" "/root/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v10.15.0/lib/node_modules/delivery-tracker-apiserver/node_modules/iconv
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-15T07_19_32_346Z-debug.log

**Comment by punkyoon** [comment]
just permission issue
