### ISSUE TITLE
안녕하세요 LTLLOGIS 추가 해주세요 

### ISSUE THREAD

**Issue by LTLLOGIS** [shlee322/delivery-tracker#122]
택배사명: LTL
택배사 사이트주소:  https://ltl.kr/order
택배사 배송조회 가능한 url :  https://ltl.kr/order
샘플송장번호  L902986433373   L902832433379   L902866433364

**Comment by shlee322** [comment]
안녕하세요.

운송업체 추가 프로세스가 변경되어 이슈 Close 합니다.

해당 운송업체가 필요하신 경우 https://tracker.delivery/request-additional-carrier 를 참고 부탁드립니다.

감사합니다.
