### ISSUE TITLE
안녕하세요. 수정요청드립니다.

### ISSUE THREAD

**Issue by minseok11** [shlee322/delivery-tracker#126]
delivery-tracker/packages/apiserver/carriers/kr.cjlogistics/index.js

line 6  STATUS_MAP 에 

RMN: { id: 'product_return', text: '반품배송예정' },

추가요청드립니다.

**Comment by shlee322** [comment]
택배사 마다 다른 경우가 있기에 현재는 반품 관련 status 를 제공하지 않고 있습니다.
향후 확장 스펙으로 고려하도록 하겠습니다.

**Comment by shlee322** [comment]
Close the issue because the codebase has changed due to the v2023 deployment.
