### ISSUE TITLE
안녕하세요 용마로지스 추가 요청 드립니다.

### ISSUE THREAD

**Issue by mmjmj** [shlee322/delivery-tracker#128]
택배사명: yongmalogis
택배사 사이트주소: http://yongmalogis.co.kr/
택배사 배송조회 가능한 url : https://eis.yongmalogis.co.kr/dm/DmTrc060?ordno={송장번호}
샘플송장번호 ..가 없어요ㅠ 금방 금방 없어지네여..

감사합니다..

**Comment by shlee322** [comment]
안녕하세요.

운송업체 추가 프로세스가 변경되어 이슈 Close 합니다.

해당 운송업체가 필요하신 경우 https://tracker.delivery/request-additional-carrier 를 참고 부탁드립니다.

감사합니다.
