### ISSUE TITLE
[한진택배] Request failed with status code 403 에러발생

### ISSUE THREAD

**Issue by lim-jong-woo** [shlee322/delivery-tracker#131]
한진택배 모든 송장번호 조회시 1. Delivery Tracker 홈페이지 배송 조회 API에서도,2. 직접 GET 요청해도 'Request failed with status code 403'이 발생합니다.

추가로 한진택배 사이트에서 조회 할때는 이상이 없습니다.( 샘플 송장번호 : 422818520622 )
https://www.hanjin.co.kr/kor/CMS/DeliveryMgr/WaybillResult.do?mCode=MN038&wblnum=422818520622&schLang=KR&wblnumText=

바쁘시겠지만 확인해주시면 감사하겠습니다.

**Comment by shlee322** [comment]
전반적인 구조 개선으로 해결되었습니다. 동일 이슈 발생시 새로 이슈 등록 부탁드립니다. 감사합니다.

**Comment by seungholee-dev** [comment]
안녕하세요, @shlee322 상혁님 :) 

혹시 어떤 구조 개선으로 해결하셨는지 여쭙고 싶습니다! :) 
감사합니다.

**Comment by shlee322** [comment]
https://github.com/shlee322/delivery-tracker/discussions/175#discussioncomment-6706987 에서 답변드리겠습니다.
