### ISSUE TITLE
GS Postbox 택배 조회 불가

### ISSUE THREAD

**Issue by nain311** [shlee322/delivery-tracker#135]
GS Postbox 택배가 조회 불가능 합니다 ㅠ

운송장 번호 210076467112

**Comment by allieus** [comment]
팝업이 뜨는 방식으로 변경되었나 봅니다.

https://www.cvsnet.co.kr/invoice/tracking.do?invoice_no=210076467112

**Comment by shlee322** [comment]
#185 에서 처리되었습니다.
