### ISSUE TITLE
종종 504 Gateway Time-out 오류가 발생합니다.

### ISSUE THREAD

**Issue by huhudaddy** [shlee322/delivery-tracker#136]
안녕하세요, 개발자님 
정말 좋은 서비스를 제공해주셔서 진심으로 감사드립니다.

택배사 무관하게 요즘 배송조회시 종종 502 Bad Gateway / 504 Gateway Time-out 이 발생하는데요
약 5번 새로고침하면 2번정도 발생하는 것 같습니다.

제가 연동을 잘 못하는건지 아니면 서버에 조금 문제가 있는건지 궁금합니다.
감사합니다.

**Comment by shlee322** [comment]
전반적인 구조 개선으로 해결되었습니다. 동일 이슈 발생시 새로 이슈 등록 부탁드립니다. 감사합니다.
