### ISSUE TITLE
CJ대한통운 502/504 문의드립니다

### ISSUE THREAD

**Issue by banana0117** [shlee322/delivery-tracker#139]
안녕하세요
어제 문제해결이 되었다고 답변해주신 것 보았고 
테스트 결과 문제가 해결되었었습니다.

지금 다시 확인해보니
어제와 같은 증상이 발생하고 있습니다.

감사합니다.

**Comment by graywavve** [comment]
로젠택배에서도 발생합니다.

개발자님 부탁드립니다~!

**Comment by shlee322** [comment]
복구되었습니다. 지속적으로 모니터링 해보도록 하겠습니다. 감사합니다.
