### ISSUE TITLE
API 속도 저하

### ISSUE THREAD

**Issue by 4leaf-peb** [shlee322/delivery-tracker#142]
현재 api 이용중인데 속도 저하가 너무 심합니다. 혹시 api 속도 저하에 대한 어떤 문제 있는건가요 ?

**Comment by shlee322** [comment]
확인해보도록 하겠습니다. 감사합니다.

**Comment by shlee322** [comment]
트래픽 증가로 전반적인 아키텍처 개선하여 대응하였습니다. 감사합니다.
