### ISSUE TITLE
로젠택배 배송완료후 배송출발이나 추가 status 가 붙으면 state의 마지막 상태가 마지막 status값을 딸아 가는거 같습니다.

### ISSUE THREAD

**Issue by pointsiga1** [shlee322/delivery-tracker#148]
로젠택배 배송완료후 배송출발이나 추가 status 가 붙으면 state의 마지막 상태가 마지막 status값을 따라 가는거 같습니다.
그래서 배송완료이나 마지막데이터 묶음에 status값이 붙어 배송출발로 나와 배송완료 처리가 되지않아 불필요한 요청을 계속 보내고 있는것으로 보여집니다. 혹시 수정이 가능할까요? 

개발자님 덕분에 정말 잘 사용하고 있습니다. ^^ 몇달전에 웹훅관련 메일도 보냈었는데 바쁘셨는지 답장이 없으셔서 이번에 문제발생된 김에 문의남겨봅니다. 
--------------------------------------------------------------------------------------------------------
(링크형 정상적으로 배송완료 표시되는 데이터이나 api에서 state값만 배송완료 시점에도 배송출발로 확인됨)
로젠택배 = https://tracker.delivery/#/kr.logen/ = 33419871052/33401222956/ [배송완료] 
                   https://apis.tracker.delivery/carriers/kr.logen/tracks/ = "state":{"id":"out_for_delivery","text":"배송출발"}
`{"from":{"name":"인***","time":"2022-08-01T21:10:00+09:00"},"to":{"name":"김****","time":null},"state":{"id":"out_for_delivery","text":"배송출발"},"progresses":[{"time":"2022-08-01T21:10:00+09:00","location":{"name":"대전센터"},"status":{"id":"at_pickup","text":"상품인수"},"description":"발송점: 터미널입고, 도착점: 남세종에서 도착하였습니다."},{"time":"2022-08-01T21:14:00+09:00","location":{"name":"대전센터"},"status":{"id":"in_transit","text":"이동중"},"description":"발송점: 터미널출고, 도착점: 이천센터(으)로 출발하였습니다."},{"time":"2022-08-02T03:08:00+09:00","location":{"name":"이천센터"},"status":{"id":"at_pickup","text":"상품인수"},"description":"발송점: 터미널입고, 도착점: 대전센터에서 도착하였습니다."},{"time":"2022-08-02T03:10:00+09:00","location":{"name":"이천센터"},"status":{"id":"in_transit","text":"이동중"},"description":"발송점: 터미널출고, 도착점: 동용산(으)로 출발하였습니다., 담당직원: 0505-278-8212"},{"time":"2022-08-02T09:19:00+09:00","location":{"name":"동용산"},"status":{"id":"in_transit","text":"이동중"},"description":"발송점: 배송입고, 도착점: 동용산지점에 도착했습니다., 담당직원: 용산 기본, 영업소: 용산 기본, 연락처: 02-796-5484"},{"time":"2022-08-02T09:20:00+09:00","location":{"name":"남용산"},"status":{"id":"delivered","text":"배송완료"},"description":"발송점: 배송완료, 도착점: 고객님께 물품을 전달하였습니다., 담당직원: 최성진, 인수자: 현관/문앞, 영업소: ***, 연락처: ========"},{"time":"2022-08-02T09:20:00+09:00","location":{"name":"남용산"},"status":{"id":"out_for_delivery","text":"배송출발"},"description":"발송점: 배송출고, 도착점: 고객님께 물품을 배달 준비 중입니다., 담당직원: 배송예정, 인수자: 14시~16시, 영업소: 최성진, 연락처: **********"}],"carrier":{"id":"33401222956","name":"로젠택배","tel":"+8215889988"}}
`

(링크형 배송완료 위에 배송출발or이동중이 추가됨 api또한 동일)
로젠택배 = https://tracker.delivery/#/kr.logen/ = 33405322285/33416893812 [배송출발/이동중]
                   https://apis.tracker.delivery/carriers/kr.logen/tracks/ = "state":{"id":"out_for_delivery","text":"배송출발or이동중"}
`{"from":{"name":"인***","time":"2022-08-01T21:10:00+09:00"},"to":{"name":"신**","time":null},"state":{"id":"out_for_delivery","text":"배송출발"},"progresses":[{"time":"2022-08-01T21:10:00+09:00","location":{"name":"대전센터"},"status":{"id":"at_pickup","text":"상품인수"},"description":"발송점: 터미널입고, 도착점: 남세종에서 도착하였습니다."},{"time":"2022-08-01T21:12:00+09:00","location":{"name":"대전센터"},"status":{"id":"in_transit","text":"이동중"},"description":"발송점: 터미널출고, 도착점: 원주센터(으)로 출발하였습니다."},{"time":"2022-08-02T03:01:00+09:00","location":{"name":"원주센터"},"status":{"id":"at_pickup","text":"상품인수"},"description":"발송점: 터미널입고, 도착점: 대전센터에서 도착하였습니다."},{"time":"2022-08-02T03:02:00+09:00","location":{"name":"원주센터"},"status":{"id":"in_transit","text":"이동중"},"description":"발송점: 터미널출고, 도착점: 서양평(으)로 출발하였습니다., 담당직원: 0505-278-8328"},{"time":"2022-08-02T09:12:00+09:00","location":{"name":"서양평"},"status":{"id":"in_transit","text":"이동중"},"description":"발송점: 배송입고, 도착점: 서양평지점에 도착했습니다., 담당직원: 이양평, 영업소: 이양평, 연락처: ********"},{"time":"2022-08-02T09:12:00+09:00","location":{"name":"서양평"},"status":{"id":"delivered","text":"배송완료"},"description":"발송점: 배송완료, 도착점: 고객님께 물품을 전달하였습니다., 담당직원: 박종욱, 인수자: 현관/문앞, 영업소: 박종욱, 연락처: *********"},{"time":"2022-08-02T09:12:00+09:00","location":{"name":"서양평"},"status":{"id":"out_for_delivery","text":"배송출발"},"description":"발송점: 배송출고, 도착점: 고객님께 물품을 배달 준비 중입니다., 담당직원: 배송예정, 인수자: 18시~21시, 영업소: 박종욱, 연락처: ****"}],"carrier":{"id":"33405322285","name":"로젠택배","tel":"+8215889988"}}`

**Comment by allieus** [comment]
@pointsiga1 : 아래 코드에서 `shippingInformation.progresses` 배열의 마지막 값을 `state` 값에 할당하는 데, 해당 페이지의 HTML 내역과 아래 코드를 통해 생성되는 `shippingInformation.progresses` 값을 확인해보시면 원인을 찾으실 수 있지 않으실까 싶네요.

https://github.com/shlee322/delivery-tracker/blob/master/packages/apiserver/carriers/kr.logen/index.js#L86

**Comment by shlee322** [comment]
Close the issue because the codebase has changed due to the v2023 deployment.
