### ISSUE TITLE
한진택배 api 오류가 발생합니다.

### ISSUE THREAD

**Issue by BongKyuKim** [shlee322/delivery-tracker#150]
아래처럼 api 호출하면 아래와 같이 에러가 발생합니다.
https://apis.tracker.delivery/carriers/kr.hanjin/tracks/530727039920

{
  "message": "Please try again in a few minutes"
}

한진택배에서 조회하면 정상적으로 보이고요.
https://www.hanjin.co.kr/kor/CMS/DeliveryMgr/WaybillResult.do?mCode=MN038&schLang=KR&wblnumText2=530727039920

어떤 송장은 정상적으로 보이고 몇몇 송장은 문제가 발생하고...
요사이 문제가 발생하는게 늘어나는 거 같습니다.

원인이 뭔지 모르겠네요.
조치 부탁드립니다.

**Comment by shlee322** [comment]
최적화를 위하여 택배 추적 과정에 queue 가 추가되었습니다.
해당 에러가 발생하는 경우 n초 후 다시 요청하시면 정상적인 결과를 수신 할 수 있습니다.
queue 가 없는 상태로 호출하고 싶은경우 Self-Hosting 버전으로 이용 부탁드립니다.

감사합니다.
