### ISSUE TITLE
발렉스 택배사 추가해주세요

### ISSUE THREAD

**Issue by ss4076** [shlee322/delivery-tracker#164]
개발자님께서 작성하신 배송관련 API 잘 사용하고 있습니다.

추가적으로 발랙스 택배사도 추가해주시면 감사하겠습니다.

**Comment by shlee322** [comment]
안녕하세요.

운송업체 추가 프로세스가 변경되어 이슈 Close 합니다.

해당 운송업체가 필요하신 경우 https://tracker.delivery/request-additional-carrier 를 참고 부탁드립니다.

감사합니다.
