### ISSUE TITLE
API 통신 속도 문의

### ISSUE THREAD

**Issue by ShineDragon83** [shlee322/delivery-tracker#165]
안녕하세요. 덕분에 택배사 정보를 잘 사용하고 있습니다.
문의사항이 있어서 글을 남깁니다.
API 통신속도가 개발 초기와 지금 차이가 많이 나는데요.
지금은 건당 조회 속도가 약 2~3초 정도 걸립니다.
저희쪽 문제인지는 모르겠지만 혹시 그 정도 시간이 걸리는게 맞는지 궁금합니다.

**Comment by shlee322** [comment]
캐싱되어있지 않은 운송장 조회의 경우 사용자의 편의를 위해 택배사에 해당 운송장 조회 이후 응답을 하게 됩니다.
이때 2~3초 가량 소요될 수 있습니다.
