### ISSUE TITLE
Self-Host Error

### ISSUE THREAD

**Issue by updaun** [shlee322/delivery-tracker#169]
서버를 실행하면 롯데 택배까지만 불러오고 그 뒤로 진행되지 않습니다. 해결 방법이 있을까요?

```
:~/projects/delivery-tracker$ delivery-tracker-apiserver

load carrier kr.cjlogistics
load carrier kr.cupost
load carrier kr.cvsnet
load carrier kr.epost
load carrier kr.hanjin
load carrier kr.logen
load carrier kr.lotte
```

**Comment by shlee322** [comment]
최신 버전을 clone 해서 사용 후 같은 문제가 발생하는 경우 문의 바랍니다.

**Comment by updaun** [comment]
![image](https://github.com/shlee322/delivery-tracker/assets/82289435/9bb5951f-f732-4671-b4a8-c0a7008a8451)

깃에서 최신 소스이며, 프로그램 실행이 kr.lotte 다음으로 진행되지 않는 문제가 여전히 발생하고 있습니다.

**Comment by shlee322** [comment]
v2023 에서 코드베이스가 변경되어 close 합니다.
