### ISSUE TITLE
CJ대한통운 배송상태 갱신이 되지 않습니다.

### ISSUE THREAD

**Issue by kchung1995** [shlee322/delivery-tracker#171]
CJ대한통운 `kr.cjlogistics`, 송장번호 `568833612760`
issue 작성 시점 기준으로 (2023년 5월 31일 오전 3시), 5월 30일의 배송내역이 갱신되지 않은 것으로 보입니다.
5월 27일까지의 배송상태만 조회됩니다.
CJ대한통운 공식 사이트 조회에서는 정상적으로 배송완료까지 조회됩니다.

**Comment by shlee322** [comment]
현재 정상동작 중으로 close 합니다.
