### ISSUE TITLE
롯데택배 배송조회 오류

### ISSUE THREAD

**Issue by Brightlight0721** [shlee322/delivery-tracker#174]
롯데택배 배송완료인데 배송출발 까지만 뜨네요..

**Comment by shlee322** [comment]
현재도 발생한다면 문제가 있는 운송장 번호 전달 부탁드립니다. 감사합니다.

**Comment by Brightlight0721** [comment]
감사합니다!
잘 동작하는 것 같습니다.
개발하신 프로젝트에서 많은 도움을 받고 있습니다.
다시 한번 진심으로 감사드립니다.


-----Original Message-----
