### ISSUE TITLE
CJ 대한통운 배송조회 오류 

### ISSUE THREAD

**Issue by thnotee** [shlee322/delivery-tracker#177]
안녕하세요 CJ대한통운 배송조회 오류가 발생하여 문의 드립니다.
오류내용은 배송조회 시간을 제대로 가지고오지 못하고 있습니다.

바쁘신데 죄송하지만 확인해주시면 감사합니다. 

테스트 URL : https://apis.tracker.delivery/carriers/kr.cjlogistics/tracks/577417824035

**Comment by MaGyul** [comment]
저도 똑같은 상황이네요. (운송장 번호: 575029149521)

**Comment by shlee322** [comment]
#178

**Comment by shlee322** [comment]
수정 버전 배포되었습니다. 일부 운송장의 경우 기존 cache 만료 전 까지 기존 데이터가 노출 될 수 있습니다.
