### ISSUE TITLE
return null when waybill invalid or not found

### ISSUE THREAD

**Issue by parkjg20** [shlee322/delivery-tracker#18]
안드로이드에서 Retrofit2를 이용하여 api를 이용하는데 잘못된 운송장이나, 아직 등록이 되지 않은 운송장에 대해서는 return이 null로 나옵니다. 혹시 API에서 반환해 주지 않는걸까 해서 질문 남깁니다.

**Comment by shlee322** [comment]
메일로 답변 드린 내용 첨부합니다.
-----------
친절한 답변 감사드립니다! 말씀해주신대로 에러발생시 핸들링하는 분기문을 만들어서 해결하였습니다.
 
-----Original Message-----
From: "이상혁"<shlee322@gmail.com> 
To: "박진국"<parkjg20@naver.com>; 
Cc: 
Sent: 2019-05-17 (금) 14:55:10 (GMT+09:00)
Subject: Re: 안녕하세요. 제작하신 API 사용 도중 질문드립니다.
 

현재 해당 URL에 접근하시면 404에 Message가 수신되는 것으로 볼때, 사용하시는 라이브러리가 404 Status Code가 반환되는 경우 null로 처리하는 것 같습니다.
사용하시는 클라이언트 라이브러리 쪽을 확인해보시기 바랍니다.
감사합니다.

2019년 5월 17일 (금) 오후 2:48, 박진국 <parkjg20@naver.com>님이 작성: 
https://apis.tracker.delivery/carriers/kr.hanjin/tracks/414514653334 입니다. 

현재 테스트 해 본 택배사는 한진택배와 우체국 택배입니다. 두 택배사 모두 null이 반환 되는것 같습니다.

 

-----Original Message-----
From: "이상혁"<shlee322@gmail.com> 
To: "박진국"<parkjg20@naver.com>; 
Cc: 
Sent: 2019-05-17 (금) 14:24:20 (GMT+09:00)
Subject: Re: 안녕하세요. 제작하신 API 사용 도중 질문드립니다.
 

안녕하세요. 문의 주신 프로젝트가 https://github.com/shlee322/delivery-tracker 가 맞나요?
위 프로젝트라고 가정하고 답변드리겠습니다.
 
우선 운송장 정보가 잘못되었을때 Status Code 404에 JSON으로 "message" 필드가 전송되어야 정상입니다.
 
null으로 나오는 URL을 알 수 있을까요?
 

2019년 5월 17일 (금) 오후 2:04, 박진국 <parkjg20@naver.com>님이 작성: 
Android Studio에서 Retrofit2를 이용중입니다. 

운송장 번호가 잘못되었거나 찾을 수 없을 때에는 return 값이 null로 나오는데 

혹시 API 제작시 의도하신 것인지 궁금하여 메일 보냅니다.
