### ISSUE TITLE
각 API에 대한 Limit 유무

### ISSUE THREAD

**Issue by musicianZem** [shlee322/delivery-tracker#184]
안녕하세요. 개발해주신 것과 유사한 내용을 개발하여 개인적으로 사용하고 있는 사람입니다.
공식 developers를 찾지 못해, 홈페이지에서 호출하는 내용을 저도 사용하고 있습니다.

현재 일정 시간마다 관리중인 송장번호 중 현재 미 배송 된 건에 대해 schedule로 돌려
개인 슬랙/텔레그램에 Webhook으로 전송해주는 방식으로 개발을 생각 중 입니다.

개발해주신 프로젝트도 위처럼 axios로 GET/POST로 처리해주고 계시던데
혹시, 대량의 트래픽을 요청하여 IP ban을 당하거나 한 적은 없으신지 궁금합니다.

회사별 초당/분당 최대 query 수에 대한 제약을 두어야 할지 궁금하여, 경험을 여쭤보려 합니다!

**Comment by shlee322** [comment]
안녕하세요.
대량의 트래픽은 각 택배사에게 부하를 일으킴에 따라 권장하지 않습니다.
딜리버리 트래커 클라우드 버전에서는 말씀해주신 방법을 포함하여 다양한 방법으로 이를 줄이기 위한 노력을 하고 있습니다.
아쉽지만 이러한 로직들은 현재 오픈소스로 제공하고 있지 않습니다. 😭

**Comment by musicianZem** [comment]
빠른 답변 감사합니다 ㅎㅎ
비슷한 고민을 하고계시고, 해보셨을 것 같아 문의드렸습니다!
