### ISSUE TITLE
우체국 택배 배송조회 문제

### ISSUE THREAD

**Issue by MaGyul** [shlee322/delivery-tracker#186]
우체국 택배 배송조회를 하면 from > name과 to > name이 null로 넘어옵니다.
혹시나 해서 우체국 택배 부분을 따로 다운받아서 node로 실행해봤을땐 잘 넘어오긴 합니다.

- 송장번호: 6079536471887
- API 요청
![image](https://github.com/shlee322/delivery-tracker/assets/49198230/45a25d18-15f6-4e5e-b9df-b7ed1209b9bb)
- kr.epost 직접 실행 
![image](https://github.com/shlee322/delivery-tracker/assets/49198230/150a2cc2-ebe7-43fc-8cbe-87bb64c07593)

**Comment by shlee322** [comment]
제보 감사합니다.

#185 작업으로 현재 apis.tracker.delivery 서버가 Delivery Tracker v2 버전의 V1 호환 기능으로 동작하고 있습니다.
이 영향으로 apis.tracker.delivery 의 kr.epost 의 from.name, to.name 이 노출되지 않는 것으로 파악 됩니다.

반영 후 안내드리겠습니다.

참고로 v2 의 경우 코드 공개에 앞서 마무리 작업 중에 있습니다 :)

**Comment by shlee322** [comment]
반영되었습니다. 감사합니다.
