### ISSUE TITLE
L 로 시작하는 우체국 조회 요청드립니다.

### ISSUE THREAD

**Issue by BS-HS** [shlee322/delivery-tracker#187]
LP257594783SG

조회되도록 기능 추가 부탁 드립니다.

그리고 한진택배 몇건들이 조회가 안되는 경우가 있습니다.

515596435911
515596441102

확인 부탁드립니다.

편리한 api를 오픈해주셔서 감사합니다.

**Comment by shlee322** [comment]
@BS-HS 

제보 감사합니다.

말씀해주신 형식은 우체국 내부 자체 운송장 번호가 아닌 UPU(Universal Postal Union) 형식으로 생각 됩니다.
이 경우 `kr.epost` 가 아닌 `un.upu.ems` 에서 제공하는게 맞으나, 현재 `un.upu.ems` 에서도 해당 형식을 제공하지 않는 것으로 파악되었습니다.

원인 파악 및 해결 이후 답변 드리겠습니다.

또한 전달해주신 한진택배 운송장 번호 2개의 경우 한진택배 홈페이지에서도 조회가 불가능한 것으로 파악됩니다.
해당 운송장이 존재하는 운송장이라면 해당 정보를 얻을 수 있는 방법을 알 수 있을까요?

**Comment by shlee322** [comment]
장시간 업데이트가 없어 close 합니다.
LP* 운송장(UPU) 의 경우 별도 처리 예정 입니다.
