### ISSUE TITLE
kr.cvsnet Code설정 되지 않는 문제

### ISSUE THREAD

**Issue by njovy** [shlee322/delivery-tracker#188]
Code가 UNKNOWN으로 설정됩니다.

**Comment by shlee322** [comment]
감사합니다. 일부 code에 대한 인식이 안 되는 케이스가 존재하여 ddf9692 에서 처리되었습니다.
잠시 후 Cloud 버전에도 배포될 예정 입니다.

**Comment by njovy** [comment]
@shlee322 빠른 수정 감사합니다.
