### ISSUE TITLE
api 스키마 ContactInfo 문제

### ISSUE THREAD

**Issue by Unknown123465** [shlee322/delivery-tracker#196]
ContactInfo 개요 보면
발신자, 수신자 또는 추적 이벤트의 연락처 정보를 나타낸다고 하는데
이게 발신잔지, 수신잔지 알 수가 없어서 api내에서 알아낼 수 있는 방법이 있을까요?

예전 api는 발신자, 수신자로 나뉘어졌는데 지금은 하나로 통합된거 같아서 다시 분리할 수 있을까요?

**Comment by shlee322** [comment]
안녕하세요.

`ContactInfo`는 field name이 아닌 type 으로 연락처 정보를 담고 있는 type 입니다.
예로, `TrackInfo.sender: ContactInfo`를 통해 발신자를 알 수 있으며, `TrackInfo.recipient: ContactInfo`를 통해 수신자를 알 수 있습니다.

https://tracker.delivery/docs/api-schema/objects/track-info
를 참고하여 주시기 바랍니다.

감사합니다.

**Comment by Unknown123465** [comment]
답변해주셔서 감사합니다 덕분에 해결되었습니다
