### ISSUE TITLE
특정상황에서 배송조회가 제대로 되지 않는거 같습니다.

### ISSUE THREAD

**Issue by kyungkuk** [shlee322/delivery-tracker#50]
운송장 번호는 한진 506738618960 입니다.
한진택배사이트나 네이버에서는 배송완료로 상태가 변경되었는는데
delivery-tracker 에서는 배송출발까지의 상태만 표기됩니다.
해당 운송장 번호를 한진택배에서 조회해보니, 배송완료 시간이 배송출발시간보다 빠르게
나와있던데, 이런경우에 제대로 결과가 안나오는거 같습니다.

**Comment by kyungkuk** [comment]
한진 506738618960
그렇지 않은 정상적인 상황에도 배송완료 상태로 변하지 않네요~

**Comment by shlee322** [comment]
감사합니다. 확인해보도록 하겠습니다.

**Comment by hanqyu** [comment]
동일현상인데 CJ대한통운의 경우가 있어서 알려드립니다.

배달완료 이후 시간에 배달완료보다 전의 state인 상품이동중이 찍혀있어서 해당 송장의 상태가 in_transit으로 인식하는 현상 같습니다.

CJ대한통운 630007777700입니다

**Comment by nain311** [comment]
음.. 대한통운도 같은 증상이 자주 나옵니다.. 아무래도 out_for_delivery보다 delivered가 5분일찍 되는거 보니..
배송하시는 분이 받자말자 배송완료 처리하시는거 같은데..
반품의 경우 때문에 마지막꺼를 가져오는것이 맞긴하나..
반품도 픽업단계부터 시작하니.. 픽업단계가 아닐경우 delivered가 있다면 배송완료로 구분짓도록 하면 안될까요..?ㅠ

**Comment by shlee322** [comment]
#104 에서 처리할 예정입니다.

**Comment by shlee322** [comment]
v2023 에서 lastEvent 를 제공함에 따라 close 합니다.
