### ISSUE TITLE
China Post 추가해주세요

### ISSUE THREAD

**Issue by chaemoong** [shlee322/delivery-tracker#52]

**Comment by shlee322** [comment]
향후 다국어 지원과 더불어 추가 계획을 가지고 있습니다. 지금 바로 지원은 일정상 어려울 것 같습니다.

직접 구현하셔서 PR 주시면 빠른 적용하도록 하겠습니다.

**Comment by shlee322** [comment]
안녕하세요.

운송업체 추가 프로세스가 변경되어 이슈 Close 합니다.

해당 운송업체가 필요하신 경우 https://tracker.delivery/request-additional-carrier 를 참고 부탁드립니다.

감사합니다.
