### ISSUE TITLE
배송 조회시 state 의 코드값은 어떤 것들이 있을까요?

### ISSUE THREAD

**Issue by kindcow85** [shlee322/delivery-tracker#53]
안녕하세요 따로 문서화 된 부분을 찾지 못해 깃을 통해 질문 드립니다.

배송조회 API의 response중 state의 정의된 코드값이 알고 싶습니다.

delivered : 배송완료 
..... : 집하
.....:  배송중 

혹은 해당 API를 이용하여 '집하' 상태도 조회가 가능한 것인지 궁금합니다.

감사합니다.

**Comment by shlee322** [comment]
`information_received | at_pickup | in_transit | out_for_delivery | delivered`
현재 위와 같은 상태가 존재합니다. 참고 부탁드립니다.

ps. 향후 문서를 OpenAPI 3 로 제공하도록 하겠습니다.
