### ISSUE TITLE
503 Error is occurred !

### ISSUE THREAD

**Issue by wadeyoon-blue** [shlee322/delivery-tracker#55]
안녕하세요.
그동안 훌륭한 서비스를 잘 사용하고 있었습니다. 
정말 감사합니다.
그런데 어제밤(1월 8일) 부터 API 503 에러가 나고 있습니다.
확인 요청 부탁드리겠습니다.
감사합니다.

**Comment by shlee322** [comment]
확인중이 있습니다. 연락주셔서 감사합니다.
