### ISSUE TITLE
Pantos Express 추가 부탁 드립니다. 

### ISSUE THREAD

**Issue by timefileby** [shlee322/delivery-tracker#70]
안녕하세요 

평소 delivery tracker를 애용하고 있는 이용자 입니다. 
혹시 괜찮으시다면, 운송사에 판토스 추가해주실 수 있으실까요~?

늘 감사 드리며, 건강 유의하세요 ^.^

감사합니다!!!!!!!!!!!!!!!!

**Comment by shlee322** [comment]
@timefileby 테스트 가능한 운송장 번호 전달 부탁드립니다.
혹은 언제나 택배사 추가 PR 환영 합니다.

**Comment by timefileby** [comment]
안녕하세요!

샘플 송장번호는 아래와 같습니다.
확인 부탁드립니다! 늘 감사히 잘 쓰고 있습니다. 대단히 감사합니다!

샘플 송장번호 : PEJP80583545




2020년 10월 3일 (토) 오전 1:49, Vint Sanghyeok Lee <notifications@github.com>님이
작성:

**Comment by shlee322** [comment]
안녕하세요.

운송업체 추가 프로세스가 변경되어 이슈 Close 합니다.

해당 운송업체가 필요하신 경우 https://tracker.delivery/request-additional-carrier 를 참고 부탁드립니다.

감사합니다.
