### ISSUE TITLE
cj대한통운택배조회 502 에러가 발생합니다.

### ISSUE THREAD

**Issue by staeho23** [shlee322/delivery-tracker#83]
https://tracker.delivery/guide  페이지에서 cj대한통운택배를 조회하면 주말부터 계속 Loading.. 메시지만 찍혀서 
별도로 메시지를 확인해보니 502 BadGateway 등의 메시지가 반환되는 것을 확인했습니다.

혹시 cj측에서 외부 접근을 막아서 생기는 현상일까요?

바쁘시겠지만 무슨 문제인지 알려주실 수 있으면 감사하겠습니다.

**Comment by nain311** [comment]
음.. 대한통운 조회페이지에 팝업이 생겼던데 혹시 그것때문이 아닐까요...?

**Comment by shlee322** [comment]
추석연휴중으로 확인해보겠습니다.

**Comment by shlee322** [comment]
해당 이슈와 비용 문제를 해결하고자 클라우드 버전 인프라 변경 하였습니다. (PaaS[GCP] -> IaaS[AWS])

**Comment by staeho23** [comment]
감사합니다 ^^
