### ISSUE TITLE
롯데 국제택배 추가 부탁드립니다.

### ISSUE THREAD

**Issue by zwan2** [shlee322/delivery-tracker#84]
https://www.lotteglogis.com/home/reservation/global/track

현재 API로는 롯데택배 - 국제택배 조회가 안되네요
감사합니다!

**Comment by shlee322** [comment]
테스트용으로 사용할 수 있는 운송장 번호 한개 안내 부탁드립니다.

**Comment by zwan2** [comment]
6064853449285
감사합니다

**Comment by shlee322** [comment]
안녕하세요.

운송업체 추가 프로세스가 변경되어 이슈 Close 합니다.

해당 운송업체가 필요하신 경우 https://tracker.delivery/request-additional-carrier 를 참고 부탁드립니다.

감사합니다.
