### ISSUE TITLE
롯데 택배 state가 at_pickup으로 나옵니다.

### ISSUE THREAD

**Issue by skygl** [shlee322/delivery-tracker#85]
롯데 택배의 경우 다른 택배와 다르게 progressses가 반대로 나와서 state가 가장 첫번째 배송 과정인 at_pickup으로 나오는 문제가 있는 것 같습니다.

**Comment by snaphers** [comment]
저도 동일한 현상인데 저는 반대로 나오는 경우는 아니고 배달완료 이후에 고객이 인수했다는 로그가 하나 더 찍혀버리네요.
그래서 네이버에서 택배조회를 해도 가장 최상단 상태가 상품인수로 나오네요ㅜ

**Comment by shlee322** [comment]
#104

**Comment by shlee322** [comment]
Close the issue because the codebase has changed due to the v2023 deployment.
