### ISSUE TITLE
API를 이용해서 앱 개발 시 앱에서 API테스트는 어떻게 하나요?

### ISSUE THREAD

**Issue by opensupport-ceo** [shlee322/delivery-tracker#87]
API를 이용해서 앱 개발 시 앱에서 API테스트는 어떻게 하나요?

실제 운송장 번호 입력하여 해야하는 건지,

아니면 따로 테스트 해볼 수 있는 운송장번호가 있어 

API 확인을 할 수 있는건지,

API 적용 시 테스트는 어떻게 해야하는 지 알려주시면 감사하겠습니다.

**Comment by shlee322** [comment]
본 서비스는 단순히 여러 택배사의 API를 단일 Endpoint로 제공하기 위한 서비스 입니다.
이에 따라, 별도로 테스트 운송장 번호를 저희가 제공하고 있지는 않습니다.
감사합니다.
