### ISSUE TITLE
Http GET request 요청 시 HttpResponse 의 status code 가 false 로 나오는 오류

### ISSUE THREAD

**Issue by opensupport-ceo** [shlee322/delivery-tracker#88]
Http GET request 요청 시 HttpResponse 의 status code 가 false 로 나오는 오류가 나옵니다.
실제로 response를 제대로 client에서 받았는데 status code가 true 가 아니라 false로 뜹니다.

client 코드: 
  using (var client = new HttpClient())
  {
                    using (HttpResponseMessage response = await client.GetAsync(uriStr))
                    {
                        DbgMsg = string.Format("HTTP Get Req.");
                        if (response.IsSuccessStatusCode)
                        {
                            var responseContent = response.Content.ReadAsStringAsync().Result;
                            DbgMsg = string.Format("Req Success.");
                            return false;
                        }
                        DbgMsg = string.Format($"Req. Fail-{response.IsSuccessStatusCode}");
                        return false;
                   }
  }
  return false;

여기서 실제로 response를  받았는데 , response.IsSuccessStatusCode 값이 false로 뜨네요.
API server에서 보내줄 때 status code로 확인 부탁 드립니다.

**Comment by opensupport-dev** [comment]
curl -v "https://apis.tracker.delivery/carriers/kr.cvsnet/tracks/11111"



위와 같이 명령을 내리면 status code가 "HTTP/1.1 200 OK" 가 나와야되는데

"HTTP/1.1 404 Not Found" 가 오는 걸로 확인됩니다.



테스트한 로그는 아래와 같습니다.

C:\TizenSDK\tools\ide\bin>curl -v "https://apis.tracker.delivery/carriers/kr.cvsnet/tracks/11111"

*   Trying 13.125.196.187...

* TCP_NODELAY set

* Connected to apis.tracker.delivery (13.125.196.187) port 443 (#0)

* schannel: SSL/TLS connection with apis.tracker.delivery port 443 (step 1/3)

* schannel: checking server certificate revocation

* schannel: sending initial handshake data: sending 192 bytes...

* schannel: sent initial handshake data: sent 192 bytes

* schannel: SSL/TLS connection with apis.tracker.delivery port 443 (step 2/3)

* schannel: failed to receive handshake, need more data

* schannel: SSL/TLS connection with apis.tracker.delivery port 443 (step 2/3)

* schannel: encrypted data got 4096

* schannel: encrypted data buffer: offset 4096 length 4096

* schannel: encrypted data length: 4030

* schannel: encrypted data buffer: offset 4030 length 4096

* schannel: received incomplete message, need more data

* schannel: SSL/TLS connection with apis.tracker.delivery port 443 (step 2/3)

* schannel: encrypted data got 1024

* schannel: encrypted data buffer: offset 5054 length 5054

* schannel: encrypted data length: 213

* schannel: encrypted data buffer: offset 213 length 5054

* schannel: received incomplete message, need more data

* schannel: SSL/TLS connection with apis.tracker.delivery port 443 (step 2/3)

* schannel: encrypted data got 134

* schannel: encrypted data buffer: offset 347 length 5054

* schannel: sending next handshake data: sending 126 bytes...

* schannel: SSL/TLS connection with apis.tracker.delivery port 443 (step 2/3)

* schannel: encrypted data got 274

* schannel: encrypted data buffer: offset 274 length 5054

* schannel: SSL/TLS handshake complete

* schannel: SSL/TLS connection with apis.tracker.delivery port 443 (step 3/3)

* schannel: stored credential handle in session cache

> GET /carriers/kr.cvsnet/tracks/11111 HTTP/1.1

> Host: apis.tracker.delivery

> User-Agent: curl/7.55.1

> Accept: */*

>

* schannel: client wants to read 102400 bytes

* schannel: encdata_buffer resized 103424

* schannel: encrypted data buffer: offset 0 length 103424

* schannel: encrypted data got 322

* schannel: encrypted data buffer: offset 322 length 103424

* schannel: decrypted data length: 293

* schannel: decrypted data added: 293

* schannel: decrypted data cached: offset 293 length 102400

* schannel: encrypted data buffer: offset 0 length 103424

* schannel: decrypted data buffer: offset 293 length 102400

* schannel: schannel_recv cleanup

* schannel: decrypted data returned 293

* schannel: decrypted data buffer: offset 0 length 102400

< HTTP/1.1 404 Not Found

< Date: Fri, 04 Dec 2020 07:33:53 GMT

< Content-Type: application/json; charset=utf-8

< Content-Length: 42

< Connection: keep-alive

< X-Powered-By: Express

< Access-Control-Allow-Origin: *

< ETag: W/"2a-E/EOt/ea59qYCkLbn1wauQcPkZw"

<

{"message":"조회결과가 없습니다"}* Connection #0 to host apis.tracker.delivery left intact



C:\TizenSDK\tools\ide\bin>



그럼, 확인 부탁드립니다.

**Comment by opensupport-dev** [comment]
이 이슈는 클로즈해도 될 것 같습니다.

제가 다시 확인해보니,
정상적인 운송장 번호를 입력하니 
Http status가 정상적으로 "HTTP/1.1 200 OK"  오는 것을 확인했습니다.

번거롭게 해드렸네요.
