### ISSUE TITLE
동시 트랙픽 혹은 트래픽에 제한이 어느정도 인지 알고 싶습니다.

### ISSUE THREAD

**Issue by DillonMemo** [shlee322/delivery-tracker#90]
동시트래픽 혹은 트래픽에 대해 어느정도 제한이 있는지에 대한 정보가 없어서 글 올립니다.

**Comment by shlee322** [comment]
답변이 늦어 죄송합니다. 공식적인 hard limit 은 존재하지 않습니다.
다만 안정적인 운영을 위하여 테스트 목적이 아닌 API 사용의 경우 아래 이메일로 별도 문의 부탁드립니다.
contact@tracker.delivery
