### ISSUE TITLE
2023년 Roadmap

### ISSUE THREAD

**Issue by shlee322** [shlee322/delivery-tracker#93]
안녕하세요. 딜리버리 트래커 개발자 이상혁입니다.

취미로 시작한 프로젝트인데 많은 분들이 관심 가져주시고 사용해주셔서 감사합니다.
몇달 동안 큰 업데이트가 없었는데요.

앞으로는 주말에 시간을 내서 주기적으로 프로젝트를 개선해나가고자 합니다.

~2021년2022년~2023년에는 다음과 같은 개선이 있을 것으로 예상 됩니다.
새로운 기능 제안이나 PR 은 언제든지 환영합니다.

- status 사이트 제공
- 안정적인 API 서비스 (cloud version 아키텍처 개선)
- 전반적인 코드 리팩토링 및 공식 웹사이트 개발
- 추가적인 택배사 추가
- API 개선 / 스키마 제공
- WebHook 기능 (운송장 상태 변경 시 노티)
- Proxy 기능

**Comment by shlee322** [comment]
2022년에는 꼭...

**Comment by Eumhongin** [comment]
항상응원합니다 좋은 API만들어주셔서 정말 감사합니다 ;)

**Comment by Yang-Jihoon-Busan** [comment]
응원합니다.

**Comment by ehgus8313** [comment]
항상감사합니다.

**Comment by shlee322** [comment]
2023년이 되어버렸다....

**Comment by shlee322** [comment]
위 기능들은 주말에 짬짬이 v2 버전 개발 중으로 v2에서 제공할 예정입니다.

**Comment by shlee322** [comment]
#185

**Comment by shlee322** [comment]
v2023.1 배포로 해당 작업들이 완료되어 close 합니다.
