### ISSUE TITLE
세방 택배사 추가 했으면 합니다.

### ISSUE THREAD

**Issue by davidlee-ezfarm** [shlee322/delivery-tracker#99]
세방택배

**Comment by davidlee-ezfarm** [comment]
테스트 운송장번호 : 6865458464183

**Comment by shlee322** [comment]
안녕하세요.

운송업체 추가 프로세스가 변경되어 이슈 Close 합니다.

해당 운송업체가 필요하신 경우 https://tracker.delivery/request-additional-carrier 를 참고 부탁드립니다.

감사합니다.
